### ISSUE TITLE
Feature request (very simple)

### ISSUE THREAD

**Issue by macrel** [Itvisors/mendix-CustomGroupBoxWidget#2]
Can we add open/close attribute toggle in the widget so we can have lazy loading for example by making conditional visible content? I hacked it in the widget for now for our usecase however would be usefull if it's included in the original code. 

2 easy changes needed:

**In XML file:** 

` 			<property key="openClosedAttribute" type="attribute" isPath="no" required="false">
				<caption>Openclosed attribute</caption>
				<description>Attribute that toggles upon open/close action</description>
				<attributeTypes>
					<attributeType name="Boolean"/>
				</attributeTypes>
			</property>`

**In JS file:  (main/src/components/CustomGroupBox.tsx) **
Please add the toggle attribute feature for the onlick handler. Not sure about the exact syntax but for you this would be a pretty easy change I guess. For us it doesn't need to commit, if it just toggles the attribute in client is enough. Something like this would be the compiled javascript:
`typeof openClosedAttribute !== 'undefined' && openClosedAttribute.setValue(!openClosedAttribute.value);`

**Comment by mgroeneweg** [comment]
The general idea is that the widget does not need an attribute to work. It really is nothing more than a header and body div container with some styling already supplied by Mendix. When you want to control open/closed status by an attribute, just create a div with the right classes on it

**Comment by macrel** [comment]
Thanks for the quick reply. Not sure if you understand my question. 

If it's intended by design that's fine. We don't want to control open/closed status by an attribute, we only want an attribute to be indicating whether it's open or closed. 

 It's just sometimes for performance reasons you want to know if the groupbox is expanded or collapsed. In our case we can then make the contents of the groupbox dependend on this attribute, which simulates kind of lazy loading feature. If the groupbox contains heavy datagrids for example this can be really usefull. Otherwise it will load the grid directly regardless of open/closed status.
 
 Anyway, we fixed it for ourselves so no worries if you don't want to go there.
